--show timezone;                          -- TimeZone = UTC

drop table if exists flight_log;
drop table if exists airlines;
drop table if exists airports;
drop table if exists airplanes;
drop table if exists sources;

create table flights(
    id_trans int not null,
    date_flight timestamptz not null,
    id_airline varchar(2) not null,
    id_tailnum varchar(6),
    id_flightnum int not null,
    id_airport_orig varchar(3),
    id_airport_dest varchar(3),
    time_depart_crs int,
    time_depart int,
    time_depart_delay int,
    time_taxi_out int,
    time_wheelsoff int,
    time_wheelson int,
    time_taxi_in int,
    time_arrive_crs int,
    time_arrive int,
    time_arrive_delay int,
    time_elapsed_crs int,
    time_elapsed_act int,
    stat_cancelled int,
    stat_diverted int,
    stat_miles int,          -- keep imperial measure
    primary key (id_trans)
);

create table flight_log(
    id_trans int not null,
    date_flight timestamptz not null,
    id_airline varchar(2) not null,
    id_tailnum varchar(6),
    id_flightnum int not null,
    id_airport_orig varchar(3),
    id_airport_dest varchar(3),
    time_depart_crs interval not null,
    time_depart interval,
    time_depart_delay interval,
    time_taxi_out int,
    time_wheelsoff int,
    time_wheelson int,
    time_taxi_in int,
    time_arrive_crs interval not null,
    time_arrive interval,
    time_arrive_delay interval,
    time_elapsed_crs interval,
    time_elapsed_act interval,
    stat_cancelled int,
    stat_diverted int,
    stat_miles int,          -- keep imperial measure
    primary key (id_trans)
);

create table airlines (
    id_airline varchar(2) not null,
    name varchar(30) not null,
    primary key (id_airline)
);

create table airports(
    id_airport varchar(3) not null,
    name varchar(55) not null,
    city varchar(30) not null,
    st varchar(2) not null,
    state varchar(50),                 -- (iso standard, useful?)
    primary key (id_airport)
);

create table airplanes(
    id_tailnum_orig varchar(6) not null,
    id_tailnum_valid varchar(6),      -- to hold incorrect tail numbers from client source dataset
    id_airline varchar(2) not null,    -- (could be transferred)
--    date_service_first
--    date_service_last
--    cum_miles (calc from all segments)
    primary key (id_tailnum_orig)
);

create table sources(
    id integer not null,
    priority int,
    name text,
    url text,
    note text,
    primary key (id)
);

insert into sources (id, priority, name, url, note) values
    (1, 1, 'FAA website: tail number validation', 'http://registry.faa.gov/aircraftinquiry/NNum_Inquiry.aspx', 'could create lambda function to curl with tailnum passed in data'),
    (2, 2, 'time zone IDs with DST offsets', 'http://download.geonames.org/export/dump/timeZones.txt', 'could use for more accurate calculation of time_next_day'),
    (3, 2, 'airport codes with time zone offset and DST time zone IDs', 'https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat', 'map against time zone IDs/offsets'),
    (4, 2, 'airport data', 'https://openflights.org/data.html', 'descriptions/dictionary for airports.dat file');

insert into airlines (id_airline, name) values
    ('TZ', 'ATA Airlines d/b/a ATA'),
    ('FL', 'AirTran Airways Corporation'),
    ('AS', 'Alaska Airlines Inc.'),
    ('KH', 'Aloha Airlines Inc.'),
    ('HP', 'America West Airlines Inc.'),
    ('AA', 'American Airlines Inc.'),
    ('OH', 'Comair Inc.'),
    ('CO', 'Continental Air Lines Inc.'),
    ('DL', 'Delta Air Lines Inc.'),
    ('9E', 'Endeavor Air Inc.'),
    ('MQ', 'Envoy Air'),
    ('EV', 'ExpressJet Airlines Inc.'),
    ('XE', 'ExpressJet Airlines Inc. (1)'),
    ('F9', 'Frontier Airlines Inc.'),
    ('HA', 'Hawaiian Airlines Inc.'),
    ('DH', 'Independence Air'),
    ('B6', 'JetBlue Airways'),
    ('YV', 'Mesa Airlines Inc.'),
    ('NW', 'Northwest Airlines Inc.'),
    ('OO', 'SkyWest Airlines Inc.'),
    ('WN', 'Southwest Airlines Co.'),
    ('NK', 'Spirit Air Lines'),
    ('TW', 'Trans World Airways LLC'),
    ('US', 'US Airways Inc.'),
    ('UA', 'United Air Lines Inc.'),
    ('VX', 'Virgin America');

insert into airports (id_airport, name, city, st, state) values
    ('ABE', 'Lehigh Valley International', 'Allentown/Bethlehem/Easton', 'PA', 'Pennsylvania'),
    ('ABI', 'Abilene Regional', 'Abilene', 'TX', 'Texas'),
    ('ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'NM', 'New Mexico'),
    ('ABR', 'Aberdeen Regional', 'Aberdeen', 'SD', 'South Dakota'),
    ('ABY', 'Southwest Georgia Regional', 'Albany', 'GA', 'Georgia'),
    ('ACK', 'Nantucket Memorial', 'Nantucket', 'MA', 'Massachusetts'),
    ('ACT', 'Waco Regional', 'Waco', 'TX', 'Texas'),
    ('ACV', 'Arcata', 'Arcata/Eureka', 'CA', 'California'),
    ('ACY', 'Atlantic City International', 'Atlantic City', 'NJ', 'New Jersey'),
    ('ADK', 'Adak', 'Adak Island', 'AK', 'Alaska'),
    ('ADQ', 'Kodiak Airport', 'Kodiak', 'AK', 'Alaska'),
    ('AEX', 'Alexandria International', 'Alexandria', 'LA', 'Louisiana'),
    ('AGS', 'Augusta Regional at Bush Field', 'Augusta', 'GA', 'Georgia'),
    ('AKN', 'King Salmon Airport', 'King Salmon', 'AK', 'Alaska'),
    ('ALB', 'Albany International', 'Albany', 'NY', 'New York'),
    ('ALO', 'Waterloo Regional', 'Waterloo', 'IA', 'Iowa'),
    ('AMA', 'Rick Husband Amarillo International', 'Amarillo', 'TX', 'Texas'),
    ('ANC', 'Ted Stevens Anchorage International', 'Anchorage', 'AK', 'Alaska'),
    ('ANI', 'Aniak Airport', 'Aniak', 'AK', 'Alaska'),
    ('APF', 'Naples Municipal', 'Naples', 'FL', 'Florida'),
    ('APN', 'Alpena County Regional', 'Alpena', 'MI', 'Michigan'),
    ('ART', 'Watertown International', 'Watertown', 'NY', 'New York'),
    ('ASE', 'Aspen Pitkin County Sardy Field', 'Aspen', 'CO', 'Colorado'),
    ('ATL', 'Hartsfield-Jackson Atlanta International', 'Atlanta', 'GA', 'Georgia'),
    ('ATW', 'Appleton International', 'Appleton', 'WI', 'Wisconsin'),
    ('AUS', 'Austin - Bergstrom International', 'Austin', 'TX', 'Texas'),
    ('AVL', 'Asheville Regional', 'Asheville', 'NC', 'North Carolina'),
    ('AVP', 'Wilkes Barre Scranton International', 'Scranton/Wilkes-Barre', 'PA', 'Pennsylvania'),
    ('AZA', 'Phoenix - Mesa Gateway', 'Phoenix', 'AZ', 'Arizona'),
    ('AZO', 'Kalamazoo/Battle Creek International', 'Kalamazoo', 'MI', 'Michigan'),
    ('BDL', 'Bradley International', 'Hartford', 'CT', 'Connecticut'),
    ('BET', 'Bethel Airport', 'Bethel', 'AK', 'Alaska'),
    ('BFL', 'Meadows Field', 'Bakersfield', 'CA', 'California'),
    ('BGM', 'Greater Binghamton/Edwin A. Link Field', 'Binghamton', 'NY', 'New York'),
    ('BGR', 'Bangor International', 'Bangor', 'ME', 'Maine'),
    ('BHM', 'Birmingham-Shuttlesworth International', 'Birmingham', 'AL', 'Alabama'),
    ('BIL', 'Billings Logan International', 'Billings', 'MT', 'Montana'),
    ('BIS', 'Bismarck Municipal', 'Bismarck/Mandan', 'ND', 'North Dakota'),
    ('BJI', 'Bemidji Regional', 'Bemidji', 'MN', 'Minnesota'),
    ('BKG', 'Branson Airport', 'Branson', 'MO', 'Missouri'),
    ('BLI', 'Bellingham International', 'Bellingham', 'WA', 'Washington'),
    ('BMI', 'Central Illinois Regional', 'Bloomington/Normal', 'IL', 'Illinois'),
    ('BNA', 'Nashville International', 'Nashville', 'TN', 'Tennessee'),
    ('BOI', 'Boise Air Terminal', 'Boise', 'ID', 'Idaho'),
    ('BOS', 'Logan International', 'Boston', 'MA', 'Massachusetts'),
    ('BPT', 'Jack Brooks Regional', 'Beaumont/Port Arthur', 'TX', 'Texas'),
    ('BQK', 'Brunswick Golden Isles', 'Brunswick', 'GA', 'Georgia'),
    ('BQN', 'Rafael Hernandez', 'Aguadilla', 'PR', 'Puerto Rico'),
    ('BRD', 'Brainerd Lakes Regional', 'Brainerd', 'MN', 'Minnesota'),
    ('BRO', 'Brownsville South Padre Island International', 'Brownsville', 'TX', 'Texas'),
    ('BRW', 'Wiley Post/Will Rogers Memorial', 'Barrow', 'AK', 'Alaska'),
    ('BTM', 'Bert Mooney', 'Butte', 'MT', 'Montana'),
    ('BTR', 'Baton Rouge Metropolitan/Ryan Field', 'Baton Rouge', 'LA', 'Louisiana'),
    ('BTV', 'Burlington International', 'Burlington', 'VT', 'Vermont'),
    ('BUF', 'Buffalo Niagara International', 'Buffalo', 'NY', 'New York'),
    ('BUR', 'Bob Hope', 'Burbank', 'CA', 'California'),
    ('BWI', 'Baltimore/Washington International Thurgood Marshall', 'Baltimore', 'MD', 'Maryland'),
    ('BZN', 'Bozeman Yellowstone International', 'Bozeman', 'MT', 'Montana'),
    ('CAE', 'Columbia Metropolitan', 'Columbia', 'SC', 'South Carolina'),
    ('CAK', 'Akron-Canton Regional', 'Akron', 'OH', 'Ohio'),
    ('CDC', 'Cedar City Regional', 'Cedar City', 'UT', 'Utah'),
    ('CDV', 'Merle K Mudhole Smith', 'Cordova', 'AK', 'Alaska'),
    ('CEC', 'Jack McNamara Field', 'Crescent City', 'CA', 'California'),
    ('CHA', 'Lovell Field', 'Chattanooga', 'TN', 'Tennessee'),
    ('CHO', 'Charlottesville Albemarle', 'Charlottesville', 'VA', 'Virginia'),
    ('CHS', 'Charleston AFB/International', 'Charleston', 'SC', 'South Carolina'),
    ('CIC', 'Chico Municipal', 'Chico', 'CA', 'California'),
    ('CID', 'The Eastern Iowa', 'Cedar Rapids/Iowa City', 'IA', 'Iowa'),
    ('CIU', 'Chippewa County International', 'Sault Ste. Marie', 'MI', 'Michigan'),
    ('CLD', 'McClellan-Palomar', 'Carlsbad', 'CA', 'California'),
    ('CLE', 'Cleveland-Hopkins International', 'Cleveland', 'OH', 'Ohio'),
    ('CLL', 'Easterwood Field', 'College Station/Bryan', 'TX', 'Texas'),
    ('CLT', 'Charlotte Douglas International', 'Charlotte', 'NC', 'North Carolina'),
    ('CMH', 'Port Columbus International', 'Columbus', 'OH', 'Ohio'),
    ('CMI', 'University of Illinois/Willard', 'Champaign/Urbana', 'IL', 'Illinois'),
    ('CMX', 'Houghton County Memorial', 'Hancock/Houghton', 'MI', 'Michigan'),
    ('CNY', 'Canyonlands Field', 'Moab', 'UT', 'Utah'),
    ('COD', 'Yellowstone Regional', 'Cody', 'WY', 'Wyoming'),
    ('COS', 'City of Colorado Springs Municipal', 'Colorado Springs', 'CO', 'Colorado'),
    ('COU', 'Columbia Regional', 'Columbia', 'MO', 'Missouri'),
    ('CPR', 'Casper/Natrona County International', 'Casper', 'WY', 'Wyoming'),
    ('CRP', 'Corpus Christi International', 'Corpus Christi', 'TX', 'Texas'),
    ('CRW', 'Yeager', 'Charleston/Dunbar', 'WV', 'West Virginia'),
    ('CSG', 'Columbus Airport', 'Columbus', 'GA', 'Georgia'),
    ('CVG', 'Cincinnati/Northern Kentucky International', 'Cincinnati', 'KY', 'Kentucky'),
    ('CWA', 'Central Wisconsin', 'Mosinee', 'WI', 'Wisconsin'),
    ('CYS', 'Cheyenne Regional/Jerry Olson Field', 'Cheyenne', 'WY', 'Wyoming'),
    ('DAB', 'Daytona Beach International', 'Daytona Beach', 'FL', 'Florida'),
    ('DAL', 'Dallas Love Field', 'Dallas', 'TX', 'Texas'),
    ('DAY', 'James M Cox/Dayton International', 'Dayton', 'OH', 'Ohio'),
    ('DBQ', 'Dubuque Regional', 'Dubuque', 'IA', 'Iowa'),
    ('DCA', 'Ronald Reagan Washington National', 'Washington', 'VA', 'Virginia'),
    ('DEN', 'Denver International', 'Denver', 'CO', 'Colorado'),
    ('DET', 'Coleman A. Young Municipal', 'Detroit', 'MI', 'Michigan'),
    ('DFW', 'Dallas/Fort Worth International', 'Dallas/Fort Worth', 'TX', 'Texas'),
    ('DHN', 'Dothan Regional', 'Dothan', 'AL', 'Alabama'),
    ('DIK', 'Dickinson - Theodore Roosevelt Regional', 'Dickinson', 'ND', 'North Dakota'),
    ('DLG', 'Dillingham Airport', 'Dillingham', 'AK', 'Alaska'),
    ('DLH', 'Duluth International', 'Duluth', 'MN', 'Minnesota'),
    ('DRO', 'Durango La Plata County', 'Durango', 'CO', 'Colorado'),
    ('DRT', 'Del Rio International', 'Del Rio', 'TX', 'Texas'),
    ('DSM', 'Des Moines International', 'Des Moines', 'IA', 'Iowa'),
    ('DTW', 'Detroit Metro Wayne County', 'Detroit', 'MI', 'Michigan'),
    ('DUT', 'Unalaska Airport', 'Unalaska', 'AK', 'Alaska'),
    ('DVL', 'Devils Lake Regional', 'Devils Lake', 'ND', 'North Dakota'),
    ('EAU', 'Chippewa Valley Regional', 'Eau Claire', 'WI', 'Wisconsin'),
    ('ECP', 'Northwest Florida Beaches International', 'Panama City', 'FL', 'Florida'),
    ('EFD', 'Ellington', 'Houston', 'TX', 'Texas'),
    ('EGE', 'Eagle County Regional', 'Eagle', 'CO', 'Colorado'),
    ('EKO', 'Elko Regional', 'Elko', 'NV', 'Nevada'),
    ('ELM', 'Elmira/Corning Regional', 'Elmira/Corning', 'NY', 'New York'),
    ('ELP', 'El Paso International', 'El Paso', 'TX', 'Texas'),
    ('ERI', 'Erie International/Tom Ridge Field', 'Erie', 'PA', 'Pennsylvania'),
    ('ESC', 'Delta County', 'Escanaba', 'MI', 'Michigan'),
    ('EUG', 'Mahlon Sweet Field', 'Eugene', 'OR', 'Oregon'),
    ('EVV', 'Evansville Regional', 'Evansville', 'IN', 'Indiana'),
    ('EWN', 'Coastal Carolina Regional', 'New Bern/Morehead/Beaufort', 'NC', 'North Carolina'),
    ('EWR', 'Newark Liberty International', 'Newark', 'NJ', 'New Jersey'),
    ('EYW', 'Key West International', 'Key West', 'FL', 'Florida'),
    ('FAI', 'Fairbanks International', 'Fairbanks', 'AK', 'Alaska'),
    ('FAR', 'Hector International', 'Fargo', 'ND', 'North Dakota'),
    ('FAT', 'Fresno Yosemite International', 'Fresno', 'CA', 'California'),
    ('FAY', 'Fayetteville Regional/Grannis Field', 'Fayetteville', 'NC', 'North Carolina'),
    ('FCA', 'Glacier Park International', 'Kalispell', 'MT', 'Montana'),
    ('FLG', 'Flagstaff Pulliam', 'Flagstaff', 'AZ', 'Arizona'),
    ('FLL', 'Fort Lauderdale-Hollywood International', 'Fort Lauderdale', 'FL', 'Florida'),
    ('FLO', 'Florence Regional', 'Florence', 'SC', 'South Carolina'),
    ('FNT', 'Bishop International', 'Flint', 'MI', 'Michigan'),
    ('FOE', 'Forbes Field', 'Topeka', 'KS', 'Kansas'),
    ('FSD', 'Joe Foss Field', 'Sioux Falls', 'SD', 'South Dakota'),
    ('FSM', 'Fort Smith Regional', 'Fort Smith', 'AR', 'Arkansas'),
    ('FWA', 'Fort Wayne International', 'Fort Wayne', 'IN', 'Indiana'),
    ('GCC', 'Gillette Campbell County', 'Gillette', 'WY', 'Wyoming'),
    ('GCK', 'Garden City Regional', 'Garden City', 'KS', 'Kansas'),
    ('GEG', 'Spokane International', 'Spokane', 'WA', 'Washington'),
    ('GFK', 'Grand Forks International', 'Grand Forks', 'ND', 'North Dakota'),
    ('GGG', 'East Texas Regional', 'Longview', 'TX', 'Texas'),
    ('GJT', 'Grand Junction Regional', 'Grand Junction', 'CO', 'Colorado'),
    ('GNV', 'Gainesville Regional', 'Gainesville', 'FL', 'Florida'),
    ('GPT', 'Gulfport-Biloxi International', 'Gulfport/Biloxi', 'MS', 'Mississippi'),
    ('GRB', 'Austin Straubel International', 'Green Bay', 'WI', 'Wisconsin'),
    ('GRI', 'Central Nebraska Regional', 'Grand Island', 'NE', 'Nebraska'),
    ('GRK', 'Robert Gray AAF', 'Killeen', 'TX', 'Texas'),
    ('GRR', 'Gerald R. Ford International', 'Grand Rapids', 'MI', 'Michigan'),
    ('GSO', 'Piedmont Triad International', 'Greensboro/High Point', 'NC', 'North Carolina'),
    ('GSP', 'Greenville-Spartanburg International', 'Greer', 'SC', 'South Carolina'),
    ('GST', 'Gustavus Airport', 'Gustavus', 'AK', 'Alaska'),
    ('GTF', 'Great Falls International', 'Great Falls', 'MT', 'Montana'),
    ('GTR', 'Golden Triangle Regional', 'Columbus', 'MS', 'Mississippi'),
    ('GUC', 'Gunnison-Crested Butte Regional', 'Gunnison', 'CO', 'Colorado'),
    ('GUM', 'Guam International', 'Guam', 'TT', 'U.S. Pacific Trust Territories and Possessions'),
    ('HDN', 'Yampa Valley', 'Hayden', 'CO', 'Colorado'),
    ('HIB', 'Range Regional', 'Hibbing', 'MN', 'Minnesota'),
    ('HLN', 'Helena Regional', 'Helena', 'MT', 'Montana'),
    ('HNL', 'Honolulu International', 'Honolulu', 'HI', 'Hawaii'),
    ('HOB', 'Lea County Regional', 'Hobbs', 'NM', 'New Mexico'),
    ('HOU', 'William P Hobby', 'Houston', 'TX', 'Texas'),
    ('HPN', 'Westchester County', 'White Plains', 'NY', 'New York'),
    ('HRL', 'Valley International', 'Harlingen/San Benito', 'TX', 'Texas'),
    ('HSV', 'Huntsville International-Carl T Jones Field', 'Huntsville', 'AL', 'Alabama'),
    ('HTS', 'Tri-State/Milton J. Ferguson Field', 'Ashland', 'WV', 'West Virginia'),
    ('HVN', 'Tweed New Haven', 'New Haven', 'CT', 'Connecticut'),
    ('HYA', 'Barnstable Municipal-Boardman/Polando Field', 'Hyannis', 'MA', 'Massachusetts'),
    ('HYS', 'Hays Regional', 'Hays', 'KS', 'Kansas'),
    ('IAD', 'Washington Dulles International', 'Washington', 'VA', 'Virginia'),
    ('IAG', 'Niagara Falls International', 'Niagara Falls', 'NY', 'New York'),
    ('IAH', 'George Bush Intercontinental/Houston', 'Houston', 'TX', 'Texas'),
    ('ICT', 'Wichita Dwight D Eisenhower National', 'Wichita', 'KS', 'Kansas'),
    ('IDA', 'Idaho Falls Regional', 'Idaho Falls', 'ID', 'Idaho'),
    ('ILE', 'Skylark Field', 'Killeen', 'TX', 'Texas'),
    ('ILG', 'New Castle', 'Wilmington', 'DE', 'Delaware'),
    ('ILM', 'Wilmington International', 'Wilmington', 'NC', 'North Carolina'),
    ('IMT', 'Ford', 'Iron Mountain/Kingsfd', 'MI', 'Michigan'),
    ('IND', 'Indianapolis International', 'Indianapolis', 'IN', 'Indiana'),
    ('INL', 'Falls International Einarson Field', 'International Falls', 'MN', 'Minnesota'),
    ('IPL', 'Imperial County', 'El Centro', 'CA', 'California'),
    ('ISN', 'Sloulin Field International', 'Williston', 'ND', 'North Dakota'),
    ('ISO', 'Kinston Regional Jetport at Stallings Field', 'Kinston', 'NC', 'North Carolina'),
    ('ISP', 'Long Island MacArthur', 'Islip', 'NY', 'New York'),
    ('ITH', 'Ithaca Tompkins Regional', 'Ithaca/Cortland', 'NY', 'New York'),
    ('ITO', 'Hilo International', 'Hilo', 'HI', 'Hawaii'),
    ('IYK', 'Inyokern Airport', 'Inyokern', 'CA', 'California'),
    ('JAC', 'Jackson Hole', 'Jackson', 'WY', 'Wyoming'),
    ('JAN', 'Jackson Medgar Wiley Evers International', 'Jackson/Vicksburg', 'MS', 'Mississippi'),
    ('JAX', 'Jacksonville International', 'Jacksonville', 'FL', 'Florida'),
    ('JFK', 'John F. Kennedy International', 'New York', 'NY', 'New York'),
    ('JLN', 'Joplin Regional', 'Joplin', 'MO', 'Missouri'),
    ('JMS', 'Jamestown Regional', 'Jamestown', 'ND', 'North Dakota'),
    ('JNU', 'Juneau International', 'Juneau', 'AK', 'Alaska'),
    ('KOA', 'Kona International Airport at Keahole', 'Kona', 'HI', 'Hawaii'),
    ('KSM', 'St. Mary''s Airport', 'St. Mary''s', 'AK', 'Alaska'),
    ('KTN', 'Ketchikan International', 'Ketchikan', 'AK', 'Alaska'),
    ('LAN', 'Capital Region International', 'Lansing', 'MI', 'Michigan'),
    ('LAR', 'Laramie Regional', 'Laramie', 'WY', 'Wyoming'),
    ('LAS', 'McCarran International', 'Las Vegas', 'NV', 'Nevada'),
    ('LAW', 'Lawton-Fort Sill Regional', 'Lawton/Fort Sill', 'OK', 'Oklahoma'),
    ('LAX', 'Los Angeles International', 'Los Angeles', 'CA', 'California'),
    ('LBB', 'Lubbock Preston Smith International', 'Lubbock', 'TX', 'Texas'),
    ('LBE', 'Arnold Palmer Regional', 'Latrobe', 'PA', 'Pennsylvania'),
    ('LCH', 'Lake Charles Regional', 'Lake Charles', 'LA', 'Louisiana'),
    ('LEX', 'Blue Grass', 'Lexington', 'KY', 'Kentucky'),
    ('LFT', 'Lafayette Regional Paul Fournet Field', 'Lafayette', 'LA', 'Louisiana'),
    ('LGA', 'LaGuardia', 'New York', 'NY', 'New York'),
    ('LGB', 'Long Beach Airport', 'Long Beach', 'CA', 'California'),
    ('LIH', 'Lihue Airport', 'Lihue', 'HI', 'Hawaii'),
    ('LIT', 'Bill and Hillary Clinton Nat Adams Field', 'Little Rock', 'AR', 'Arkansas'),
    ('LMT', 'Klamath Falls Airport', 'Klamath Falls', 'OR', 'Oregon'),
    ('LNK', 'Lincoln Airport', 'Lincoln', 'NE', 'Nebraska'),
    ('LNY', 'Lanai Airport', 'Lanai', 'HI', 'Hawaii'),
    ('LRD', 'Laredo International', 'Laredo', 'TX', 'Texas'),
    ('LSE', 'La Crosse Regional', 'La Crosse', 'WI', 'Wisconsin'),
    ('LWB', 'Greenbrier Valley', 'Lewisburg', 'WV', 'West Virginia'),
    ('LWS', 'Lewiston Nez Perce County', 'Lewiston', 'ID', 'Idaho'),
    ('LYH', 'Lynchburg Regional/Preston Glenn Field', 'Lynchburg', 'VA', 'Virginia'),
    ('MAF', 'Midland International', 'Midland/Odessa', 'TX', 'Texas'),
    ('MAZ', 'Eugenio Maria de Hostos', 'Mayaguez', 'PR', 'Puerto Rico'),
    ('MBS', 'MBS International', 'Saginaw/Bay City/Midland', 'MI', 'Michigan'),
    ('MCI', 'Kansas City International', 'Kansas City', 'MO', 'Missouri'),
    ('MCN', 'Middle Georgia Regional', 'Macon', 'GA', 'Georgia'),
    ('MCO', 'Orlando International', 'Orlando', 'FL', 'Florida'),
    ('MDT', 'Harrisburg International', 'Harrisburg', 'PA', 'Pennsylvania'),
    ('MDW', 'Chicago Midway International', 'Chicago', 'IL', 'Illinois'),
    ('MEI', 'Key Field', 'Meridian', 'MS', 'Mississippi'),
    ('MEM', 'Memphis International', 'Memphis', 'TN', 'Tennessee'),
    ('MFE', 'McAllen Miller International', 'Mission/McAllen/Edinburg', 'TX', 'Texas'),
    ('MFR', 'Rogue Valley International - Medford', 'Medford', 'OR', 'Oregon'),
    ('MGM', 'Montgomery Regional', 'Montgomery', 'AL', 'Alabama'),
    ('MHK', 'Manhattan Regional', 'Manhattan/Ft. Riley', 'KS', 'Kansas'),
    ('MHT', 'Manchester-Boston Regional', 'Manchester', 'NH', 'New Hampshire'),
    ('MIA', 'Miami International', 'Miami', 'FL', 'Florida'),
    ('MIB', 'Minot AFB', 'Minot', 'ND', 'North Dakota'),
    ('MKE', 'General Mitchell International', 'Milwaukee', 'WI', 'Wisconsin'),
    ('MKG', 'Muskegon County', 'Muskegon', 'MI', 'Michigan'),
    ('MKK', 'Molokai', 'Hoolehua', 'HI', 'Hawaii'),
    ('MLB', 'Melbourne International', 'Melbourne', 'FL', 'Florida'),
    ('MLI', 'Quad City International', 'Moline', 'IL', 'Illinois'),
    ('MLU', 'Monroe Regional', 'Monroe', 'LA', 'Louisiana'),
    ('MMH', 'Mammoth Lakes Airport', 'Mammoth Lakes', 'CA', 'California'),
    ('MOB', 'Mobile Regional', 'Mobile', 'AL', 'Alabama'),
    ('MOD', 'Modesto City-County-Harry Sham Field', 'Modesto', 'CA', 'California'),
    ('MOT', 'Minot International', 'Minot', 'ND', 'North Dakota'),
    ('MQT', 'Sawyer International', 'Marquette', 'MI', 'Michigan'),
    ('MRY', 'Monterey Regional', 'Monterey', 'CA', 'California'),
    ('MSN', 'Dane County Regional-Truax Field', 'Madison', 'WI', 'Wisconsin'),
    ('MSO', 'Missoula International', 'Missoula', 'MT', 'Montana'),
    ('MSP', 'Minneapolis-St Paul International', 'Minneapolis', 'MN', 'Minnesota'),
    ('MSY', 'Louis Armstrong New Orleans International', 'New Orleans', 'LA', 'Louisiana'),
    ('MTJ', 'Montrose Regional', 'Montrose/Delta', 'CO', 'Colorado'),
    ('MVY', 'Martha''s Vineyard Airport', 'Martha''s Vineyard', 'MA', 'Massachusetts'),
    ('MWH', 'Grant County International', 'Moses Lake', 'WA', 'Washington'),
    ('MYR', 'Myrtle Beach International', 'Myrtle Beach', 'SC', 'South Carolina'),
    ('OAJ', 'Albert J Ellis', 'Jacksonville/Camp Lejeune', 'NC', 'North Carolina'),
    ('OAK', 'Metropolitan Oakland International', 'Oakland', 'CA', 'California'),
    ('OGG', 'Kahului Airport', 'Kahului', 'HI', 'Hawaii'),
    ('OKC', 'Will Rogers World', 'Oklahoma City', 'OK', 'Oklahoma'),
    ('OMA', 'Eppley Airfield', 'Omaha', 'NE', 'Nebraska'),
    ('OME', 'Nome Airport', 'Nome', 'AK', 'Alaska'),
    ('ONT', 'Ontario International', 'Ontario', 'CA', 'California'),
    ('ORD', 'Chicago O''Hare International', 'Chicago', 'IL', 'Illinois'),
    ('ORF', 'Norfolk International', 'Norfolk', 'VA', 'Virginia'),
    ('ORH', 'Worcester Regional', 'Worcester', 'MA', 'Massachusetts'),
    ('OTH', 'Southwest Oregon Regional', 'North Bend/Coos Bay', 'OR', 'Oregon'),
    ('OTZ', 'Ralph Wien Memorial', 'Kotzebue', 'AK', 'Alaska'),
    ('OXR', 'Oxnard', 'Oxnard/Ventura', 'CA', 'California'),
    ('PAH', 'Barkley Regional', 'Paducah', 'KY', 'Kentucky'),
    ('PBG', 'Plattsburgh International', 'Plattsburgh', 'NY', 'New York'),
    ('PBI', 'Palm Beach International', 'West Palm Beach/Palm Beach', 'FL', 'Florida'),
    ('PDX', 'Portland International', 'Portland', 'OR', 'Oregon'),
    ('PFN', 'Bay County', 'Panama City', 'FL', 'Florida'),
    ('PHF', 'Newport News/Williamsburg International', 'Newport News/Williamsburg', 'VA', 'Virginia'),
    ('PHL', 'Philadelphia International', 'Philadelphia', 'PA', 'Pennsylvania'),
    ('PHX', 'Phoenix Sky Harbor International', 'Phoenix', 'AZ', 'Arizona'),
    ('PIA', 'General Downing - Peoria International', 'Peoria', 'IL', 'Illinois'),
    ('PIB', 'Hattiesburg-Laurel Regional', 'Hattiesburg/Laurel', 'MS', 'Mississippi'),
    ('PIE', 'St Pete Clearwater International', 'St. Petersburg', 'FL', 'Florida'),
    ('PIH', 'Pocatello Regional', 'Pocatello', 'ID', 'Idaho'),
    ('PIT', 'Pittsburgh International', 'Pittsburgh', 'PA', 'Pennsylvania'),
    ('PLN', 'Pellston Regional Airport of Emmet County', 'Pellston', 'MI', 'Michigan'),
    ('PNS', 'Pensacola International', 'Pensacola', 'FL', 'Florida'),
    ('PPG', 'Pago Pago International', 'Pago Pago', 'TT', 'U.S. Pacific Trust Territories and Possessions'),
    ('PSC', 'Tri Cities', 'Pasco/Kennewick/Richland', 'WA', 'Washington'),
    ('PSE', 'Mercedita', 'Ponce', 'PR', 'Puerto Rico'),
    ('PSG', 'Petersburg James A Johnson', 'Petersburg', 'AK', 'Alaska'),
    ('PSP', 'Palm Springs International', 'Palm Springs', 'CA', 'California'),
    ('PUB', 'Pueblo Memorial', 'Pueblo', 'CO', 'Colorado'),
    ('PVD', 'Theodore Francis Green State', 'Providence', 'RI', 'Rhode Island'),
    ('PWM', 'Portland International Jetport', 'Portland', 'ME', 'Maine'),
    ('RAP', 'Rapid City Regional', 'Rapid City', 'SD', 'South Dakota'),
    ('RDD', 'Redding Municipal', 'Redding', 'CA', 'California'),
    ('RDM', 'Roberts Field', 'Bend/Redmond', 'OR', 'Oregon'),
    ('RDU', 'Raleigh-Durham International', 'Raleigh/Durham', 'NC', 'North Carolina'),
    ('RFD', 'Chicago/Rockford International', 'Rockford', 'IL', 'Illinois'),
    ('RHI', 'Rhinelander/Oneida County', 'Rhinelander', 'WI', 'Wisconsin'),
    ('RIC', 'Richmond International', 'Richmond', 'VA', 'Virginia'),
    ('RKS', 'Rock Springs Sweetwater County', 'Rock Springs', 'WY', 'Wyoming'),
    ('RNO', 'Reno/Tahoe International', 'Reno', 'NV', 'Nevada'),
    ('ROA', 'Roanoke Blacksburg Regional Woodrum Field', 'Roanoke', 'VA', 'Virginia'),
    ('ROC', 'Greater Rochester International', 'Rochester', 'NY', 'New York'),
    ('ROP', 'Benjamin Taisacan Manglona International', 'Rota', 'TT', 'U.S. Pacific Trust Territories and Possessions'),
    ('ROR', 'Babelthuap', 'Koror', 'TT', 'U.S. Pacific Trust Territories and Possessions'),
    ('ROW', 'Roswell International Air Center', 'Roswell', 'NM', 'New Mexico'),
    ('RST', 'Rochester International', 'Rochester', 'MN', 'Minnesota'),
    ('RSW', 'Southwest Florida International', 'Fort Myers', 'FL', 'Florida'),
    ('SAF', 'Santa Fe Municipal', 'Santa Fe', 'NM', 'New Mexico'),
    ('SAN', 'San Diego International', 'San Diego', 'CA', 'California'),
    ('SAT', 'San Antonio International', 'San Antonio', 'TX', 'Texas'),
    ('SAV', 'Savannah/Hilton Head International', 'Savannah', 'GA', 'Georgia'),
    ('SBA', 'Santa Barbara Municipal', 'Santa Barbara', 'CA', 'California'),
    ('SBN', 'South Bend International', 'South Bend', 'IN', 'Indiana'),
    ('SBP', 'San Luis County Regional', 'San Luis Obispo', 'CA', 'California'),
    ('SCC', 'Deadhorse Airport', 'Deadhorse', 'AK', 'Alaska'),
    ('SCE', 'University Park', 'State College', 'PA', 'Pennsylvania'),
    ('SDF', 'Louisville International-Standiford Field', 'Louisville', 'KY', 'Kentucky'),
    ('SEA', 'Seattle/Tacoma International', 'Seattle', 'WA', 'Washington'),
    ('SFO', 'San Francisco International', 'San Francisco', 'CA', 'California'),
    ('SGF', 'Springfield-Branson National', 'Springfield', 'MO', 'Missouri'),
    ('SGU', 'St George Regional', 'St. George', 'UT', 'Utah'),
    ('SHD', 'Shenandoah Valley Regional', 'Staunton', 'VA', 'Virginia'),
    ('SHV', 'Shreveport Regional', 'Shreveport', 'LA', 'Louisiana'),
    ('SIT', 'Sitka Rocky Gutierrez', 'Sitka', 'AK', 'Alaska'),
    ('SJC', 'Norman Y. Mineta San Jose International', 'San Jose', 'CA', 'California'),
    ('SJT', 'San Angelo Regional/Mathis Field', 'San Angelo', 'TX', 'Texas'),
    ('SJU', 'Luis Munoz Marin International', 'San Juan', 'PR', 'Puerto Rico'),
    ('SLC', 'Salt Lake City International', 'Salt Lake City', 'UT', 'Utah'),
    ('SMF', 'Sacramento International', 'Sacramento', 'CA', 'California'),
    ('SMX', 'Santa Maria Public/Capt. G. Allan Hancock Field', 'Santa Maria', 'CA', 'California'),
    ('SNA', 'John Wayne Airport-Orange County', 'Santa Ana', 'CA', 'California'),
    ('SPI', 'Abraham Lincoln Capital', 'Springfield', 'IL', 'Illinois'),
    ('SPN', 'Francisco C. Ada Saipan International', 'Saipan', 'TT', 'U.S. Pacific Trust Territories and Possessions'),
    ('SPS', 'Sheppard AFB/Wichita Falls Municipal', 'Wichita Falls', 'TX', 'Texas'),
    ('SRQ', 'Sarasota/Bradenton International', 'Sarasota/Bradenton', 'FL', 'Florida'),
    ('STC', 'St. Cloud Regional', 'St. Cloud', 'MN', 'Minnesota'),
    ('STL', 'Lambert-St. Louis International', 'St. Louis', 'MO', 'Missouri'),
    ('STT', 'Cyril E King', 'Charlotte Amalie', 'VI', 'U.S. Virgin Islands'),
    ('STX', 'Henry E. Rohlsen', 'Christiansted', 'VI', 'U.S. Virgin Islands'),
    ('SUN', 'Friedman Memorial', 'Sun Valley/Hailey/Ketchum', 'ID', 'Idaho'),
    ('SUX', 'Sioux Gateway/Col. Bud Day Field', 'Sioux City', 'IA', 'Iowa'),
    ('SWF', 'Stewart International', 'Newburgh/Poughkeepsie', 'NY', 'New York'),
    ('SYR', 'Syracuse Hancock International', 'Syracuse', 'NY', 'New York'),
    ('TEX', 'Telluride Regional', 'Telluride', 'CO', 'Colorado'),
    ('TLH', 'Tallahassee International', 'Tallahassee', 'FL', 'Florida'),
    ('TOL', 'Toledo Express', 'Toledo', 'OH', 'Ohio'),
    ('TPA', 'Tampa International', 'Tampa', 'FL', 'Florida'),
    ('TRI', 'Tri-Cities Regional TN/VA', 'Bristol/Johnson City/Kingsport', 'TN', 'Tennessee'),
    ('TTN', 'Trenton Mercer', 'Trenton', 'NJ', 'New Jersey'),
    ('TUL', 'Tulsa International', 'Tulsa', 'OK', 'Oklahoma'),
    ('TUS', 'Tucson International', 'Tucson', 'AZ', 'Arizona'),
    ('TVC', 'Cherry Capital', 'Traverse City', 'MI', 'Michigan'),
    ('TWF', 'Joslin Field - Magic Valley Regional', 'Twin Falls', 'ID', 'Idaho'),
    ('TXK', 'Texarkana Regional-Webb Field', 'Texarkana', 'AR', 'Arkansas'),
    ('TYR', 'Tyler Pounds Regional', 'Tyler', 'TX', 'Texas'),
    ('TYS', 'McGhee Tyson', 'Knoxville', 'TN', 'Tennessee'),
    ('UCA', 'Oneida County', 'Utica/Rome', 'NY', 'New York'),
    ('UST', 'Northeast Florida Regional', 'St. Augustine', 'FL', 'Florida'),
    ('UTM', 'Tunica Municipal', 'Tunica', 'MS', 'Mississippi'),
    ('VCT', 'Victoria Regional', 'Victoria', 'TX', 'Texas'),
    ('VEL', 'Vernal Regional', 'Vernal', 'UT', 'Utah'),
    ('VIS', 'Visalia Municipal', 'Visalia', 'CA', 'California'),
    ('VLD', 'Valdosta Regional', 'Valdosta', 'GA', 'Georgia'),
    ('VPS', 'Eglin AFB Destin Fort Walton Beach', 'Valparaiso', 'FL', 'Florida'),
    ('WRG', 'Wrangell Airport', 'Wrangell', 'AK', 'Alaska'),
    ('WYS', 'Yellowstone', 'West Yellowstone', 'MT', 'Montana'),
    ('XNA', 'Northwest Arkansas Regional', 'Fayetteville', 'AR', 'Arkansas'),
    ('YAK', 'Yakutat Airport', 'Yakutat', 'AK', 'Alaska'),
    ('YUM', 'Yuma MCAS/Yuma International', 'Yuma', 'AZ', 'Arizona');
